### PR TITLE
Clarify Notifications API requirements

### PR DESCRIPTION
**Pull request by JohnRiv**
This addresses #238

### CODE REVIEW

**Review by johnluther — APPROVED** [review]

**Review by jpiesing — COMMENTED** [review]
It may be worth distinguishing 2 different cases - not supporting the notifications API at all and supporting the API but not the underlying notifications framework. The first of these will go away in time because all HTML5 UAs will support the API and removing it would be hard work. What we're really addressing with this new text is the second but the proposed text sometime blurs this and seems to talk about the first.

**Comment by JohnRiv** [comment]
Great point. I'll update the PR to make it clear we are addressing the OS/platform/device not supporting a notifications framework.

**Comment by JohnRiv** [comment]
@jpiesing I pushed an update to my original language based on your comment. I certainly welcome further suggestions.

**Comment by JohnRiv** [comment]
On the 2/19/20 HATF call, there was consensus to merge this

**Pull request merged**
