### PR TITLE
Update test suite URL to 2022

### PR DESCRIPTION
**Pull request by JohnRiv**
This addresses #308

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webmediaapi/pull/309.html" title="Last updated on Oct 11, 2022, 4:27 PM UTC (6b65782)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webmediaapi/309/1ba764f...6b65782.html" title="Last updated on Oct 11, 2022, 4:27 PM UTC (6b65782)">Diff</a>

### CODE REVIEW

**Review by louaybassbouss — APPROVED** [review]
Thanks @JohnRiv LGTM

**Comment by louaybassbouss** [comment]
@JohnRiv should we wait with the merge until the new wmas2022 subdomain is online?

**Comment by JohnRiv** [comment]
@louaybassbouss yes, good idea to wait until the merge. Let us know here once it is ready.

**Comment by louaybassbouss** [comment]
the new domain for WMAS 2022 Test Suite https://webapitests2022.ctawave.org/ is ready :)

**Pull request merged**
