### PR TITLE
Add WebDriver, along with editors note that it is at-risk for now

### PR DESCRIPTION
**Pull request by davemevans**
This implements consensus reached in #71.

### CODE REVIEW

**Comment by mavgit** [comment]
Instead of the current editor's note:
> This API is at risk of removal from this list without resolution of...

I suggest the following would be clearer:
> WebDriver API is at risk of removal from this specification pending resolution of...

**Comment by davemevans** [comment]
LGTM, will apply on Monday.

**Comment by jpiesing** [comment]
Please remember that the issue that's been filed with webdriver is the simpler one of two. There remains the issue of whether existing webdriver implementations would allow a device manufacturer to limit what is being debugged to prevent third parties debugging a service providers app.

**Comment by davemevans** [comment]
Is it possible to mitigate these issues by adding some restrictions to WebDriver implementations in the Web Media Porting spec?

**Comment by jpiesing** [comment]
> Is it possible to mitigate these issues by adding some restrictions to WebDriver implementations in the Web Media Porting spec?

A lot of our design choices have been made with the goal of avoiding changes to core browser code. If browser code bases don't support restricting what can be debugged then changing this may not be practical / safe / possible for integrators even if we say something in the porting / integration spec.

**Comment by davemevans** [comment]
Surely we could define some behaviour at the porting level which must occur when webdriver is active? eg. don't present client certificates so clients can't be authenticated or similar.

**Comment by jpiesing** [comment]
> Surely we could define some behaviour at the porting level which must occur when webdriver is active? eg. don't present client certificates so clients can't be authenticated or similar.

Not all service providers use client certificates to identify / authenticate devices. In some cases, the browser will come with a tightly integrated HTTP stack so even disabling device certificates may require surgery to code that a vendor may have limited access or limited expertise.

**Pull request merged**
